#!/usr/bin/env python3
import os
import urllib.parse
import html

# 1. Output the mandatory CGI HTTP header and a blank line
print("Content-Type: text/html\n")

# 2. Extract the query string from the environment variables
query_string = os.environ.get("QUERY_STRING", "")

# 3. Parse the query string into a dictionary of lists
parsed_query = urllib.parse.parse_qs(query_string)

# 4. Extract the 'name' parameter (default to 'Guest' if not provided)
user_name = parsed_query.get("name", ["Guest"])[0]

# 5. Sanitize the variable to prevent XSS when rendering HTML
safe_name = html.escape(user_name)

# 6. Render the custom HTML page
html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dynamic CGI Page</title>
    <style>
        body {{ font-family: sans-serif; margin: 40px; }}
        .greeting {{ color: #2c3e50; }}
    </style>
</head>
<body>
    <h1 class="greeting">Hello, {safe_name}!</h1>
    <p>This HTML was dynamically generated by the Python CGI script.</p>
</body>
</html>
"""

print(html_content)
