
events{}

http {
	server {
		server_name webserv_test;
		listen 127.0.0.1:3000;

		client_max_body_size 10m;

		root ./www/webserv_website;

		error_page 403 ./www/webserv_website/errors/403.html;
		error_page 404 ./www/webserv_website/errors/404.html;
		error_page 405 ./www/webserv_website/errors/405.html;
		error_page 408 ./www/webserv_website/errors/408.html;
		error_page 413 ./www/webserv_website/errors/413.html;
		error_page 500 ./www/webserv_website/errors/500.html;

		location / {
			limit_except GET {
				deny all;
			}

			index index.html;

		}

		location /upload {
			limit_except GET POST DELETE {
				deny all;
			}

			autoindex on;
			dav_methods POST DELETE;
		}

		location /protected {
			limit_except GET {
				deny all;
			}

			autoindex off;
		}


		location /old-page {
			limit_except GET POST DELETE {
				deny all;
			}

			return 301 /new-page;
		}


		location /new-page {
			limit_except GET POST DELETE {
				deny all;
			}

			index index.html;
		}

		location /errors {
			limit_except GET {
				deny all;
			}
		}

		location /cgi-bin {
			limit_except GET POST {
				deny all;
			}

			cgi_pass .py /usr/bin/python3;
			cgi_pass .js /usr/bin/node;

		}
	}
}
